baseURL = 'https://ying-ya-rebirth.github.io/'
defaultContentLanguage = 'zh'
title = '宇宝饭'
theme = "github-style"

[languages]
  [languages.zh]
    contentDir = 'content/zh'
    languageName = 'Chinese'
    title = '宇宝饭'
    weight = 1

    [languages.fr]
    contentDir = 'content/fr'
    languageName = 'French'
    title = "Le délice d'Yubao"
    weight = 2

    [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = 'YuBaoRice'
    weight = 3

staticDir = "static"

[params]
  author = "蚜英"
  description = "XXXX"
  github = "ying-ya-rebirth"
  email = "yingya218@gmail.com"
  keywords = "blog, google analytics"
  rss = true
  userStatusEmoji = "🐱"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-white.png"
  location = "Asia"
  enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]
  enableSearch = true 

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "Your Github username"
    admin = "Your Github username"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [outputs]
  home = ["HTML", "RSS", "JSON"]